### ISSUE TITLE
e.on is not a function error in latest version

### ISSUE THREAD

**Issue by james-martin-jd** [solid/query-ldflex#50]
After upgrading to 2.8.0 (and ensuring I was on node v12) I started noticing an error in the console, seemingly one message per ldflex query. The error is:

```
Uncaught (in promise) TypeError: e.on is not a function
10LinkedRdfSourcesAsyncRdfIterator.js:91 Uncaught (in promise) TypeError: e.on is not a function
```

This was observed on multiple developer machines, and at least one server deployment. After rolling back to 2.6.0 the error went away. It did not appear to impede the actual queries from executing, but we rolled back anyway to prevent console errors.

**Comment by RubenVerborgh** [comment]
Mmm… if anyone has a reproducible example, that would be helpful. Will try to find one.

**Comment by DoctorBud** [comment]
Attached are `ldflexbug.html` and `ldflexbug_popup.html`, which are sufficient to demonstrate the bug in 2.8.0 (login is required, so you'll need to serve up both files via an HTTP server). I have the example currently configured to use 2.7.0 and it works fine. Editing the `<script>` tag to use 2.8.0 will result in the error being reported in console. Note that data is still being returned successfully despite the error message.

*I needed to use a `.txt` file extension to attach these files to the GitHub issue*

- [ldflexbug.html.txt](https://github.com/solid/query-ldflex/files/3975195/ldflexbug.html.txt)
- [ldflexbug_popup.html.txt](https://github.com/solid/query-ldflex/files/3975197/ldflexbug_popup.html.txt)

**Comment by RubenVerborgh** [comment]
Thanks @DoctorBud, I appreciate it!
